version: '3.5'
services: 
  kong-database:
    image: postgres:11.2-alpine
    container_name: kong-database
    volumes:
      - "./volumes/kong/db:/var/lib/postgresql/data"
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    restart: always

  kong-gateway:
    image: kong:1.1.1-alpine
    container_name: kong-gateway
    links: 
      - "kong-database:kong-database"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    restart: always
  
  kong-migrations:
    image: kong:1.1.1-alpine
    container_name: kong-migrations
    command: kong migrations bootstrap
    environment: 
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    links:
      - "kong-database:kong-database"

  konga-admin:
    image: pantsel/konga
    container_name: kong-admin
    ports: 
      - "1337:1337"
    environment: 
      NODE_ENV: production
    volumes: 
      - "./volumes/konga/data:/app/kongadata"
    restart: always